In [16]:
from IPython import display
import numpy as np
import sympy as sym
import numpy.linalg as la


## Matritzen

### Berechnungen

#### Inner product

In [17]:
# Vectors as 1D numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a= ", a)
print("b= ", b)
print("\ninner:", np.inner(a, b))
print("dot:", np.dot(a, b))

a=  [1 2 3]
b=  [4 5 6]

inner: 32
dot: 32


#### Dot product

In [18]:
# Matrices as ndarray objects
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [8, 9, 10]])
print("a", type(a))
print(a)
print("\nb", type(b))
print(b)

# Matrices as matrix objects
c = np.matrix([[1, 2], [3, 4]])
d = np.matrix([[5, 6, 7], [8, 9, 10]])
print("\nc", type(c))
print(c)
print("\nd", type(d))
print(d)
print("\ndot product of two ndarray objects")
print(np.dot(a, b))
print("\ndot product of two matrix objects")
print(np.dot(c, d))

a <class 'numpy.ndarray'>
[[1 2]
 [3 4]]

b <class 'numpy.ndarray'>
[[ 5  6  7]
 [ 8  9 10]]

c <class 'numpy.matrix'>
[[1 2]
 [3 4]]

d <class 'numpy.matrix'>
[[ 5  6  7]
 [ 8  9 10]]

dot product of two ndarray objects
[[21 24 27]
 [47 54 61]]

dot product of two matrix objects
[[21 24 27]
 [47 54 61]]


#### Transpose

In [19]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print("a = ")
print(a)

print("\nWith np.transpose(a) function")
print(np.transpose(a))

print("\nWith ndarray.transpose() method")
print(a.transpose())

print("\nWith ndarray.T short form")
print(a.T)

a = 
[[1 2]
 [3 4]
 [5 6]]

With np.transpose(a) function
[[1 3 5]
 [2 4 6]]

With ndarray.transpose() method
[[1 3 5]
 [2 4 6]]

With ndarray.T short form
[[1 3 5]
 [2 4 6]]


#### Trace

In [20]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
print("\nTrace:", a.trace())
print("Trace:", sum(a.diagonal()))

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Trace: 7
Trace: 7


#### Rank

In [21]:
a = np.arange(1, 10)
a.shape = (3, 3)
print("a = ")
print(a)
rank = np.linalg.matrix_rank(a)
print("\nRank:", rank)

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank: 2


#### Determinant

In [22]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 5.0


#### True inverse

In [23]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))
inv = np.linalg.inv(a)
print("\nInverse of a = ")
print(inv)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 5.0

Inverse of a = 
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


#### Pseudo inverse

In [24]:
a = np.array([[2, 8],
               [1, 4]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))
pinv = np.linalg.pinv(a)
print("\nPseudo Inverse of a = ")
print(pinv)

a = 
[[2 8]
 [1 4]]

Determinant: 0.0

Pseudo Inverse of a = 
[[0.02352941 0.01176471]
 [0.09411765 0.04705882]]


#### Eigenvalues and eigenvectors

In [25]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
w, v = np.linalg.eig(a)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Eigenvalues:
[5. 1. 1.]

Eigenvectors:
[[-0.57735027 -0.90453403  0.82529864]
 [-0.57735027  0.30151134 -0.52125218]
 [-0.57735027  0.30151134  0.21720572]]


In [26]:
p = [1, 5, 6] # x^2, x^1, x^0
roots = np.roots(p)
print(roots)

coeff = [1, -6, 11, -6] # x^3 , x^2, x^1, x^0
print(np.roots(coeff))

[-3. -2.]
[3. 2. 1.]


### Diagonalisierbarkeit

In [27]:
ar = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])

# check if the matrix ar is diagonal
np.array_equal(ar, np.diag(np.diag(ar)))



False

In [28]:
# create a matrix
ar = np.array([
    [1, 1, 0],
    [0, 2, 0],
    [0, 0, 3]
])
# check if the matrix ar is diagonal
print(np.array_equal(ar, np.diag(np.diag(ar))))

False


### Orthogonalität

quatratische Matrix !!

$$
Q^T \cdot Q = I
$$

I -> Einheitsmatrix

[0,1]
[1,0]

In [29]:

a = np.array([[0, 1],
              [1, 0]])
b = np.array([[1, 0, 2],
              [2, 2, -1],
              [2, -2, 0],
              [0, 1, 2]])

t = np.transpose(a)
d = np.dot(a,t)
# or
d = a.dot(a.T)
#
print(d)
c = np.count_nonzero(d - np.diag(np.diagonal(d)))
print(c) # if = 0 then Matrix is orthogonal


[[1 0]
 [0 1]]
0


In [30]:
a = np.array([[1, 0, 2],
              [2, 2, -1],
              [2, -2, 0],
              [0, 1, 2]])
# first column:
c1 = a[:, 0]
# second column:
c2 = a[:, 1]
# third column:
c3 = a[:, 2]
# first column:
r1 = a[0, :]
# second column:
r2 = a[1, :]
# third column:
r3 = a[2, :]

# check if columns are orthogonal to each other
print(np.dot(c1,c2)) # =0 if orthogonal
print(np.dot(c1,c3)) # =0 if orthogonal
print(np.dot(c2,c3)) # =0 if orthogonal


0
0
0
